[build]
  publish = "out/"
  command = "npm run export"
  environment = { DATABASE_URL = "file:./octopi.db" }

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/media/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"